repos:
  - repo: local
    hooks:
      - id: autopep8-custom
        name: autopep8 custom formatting
        entry: bash -c 'git ls-files "*.py" | xargs autopep8 --in-place --pep8-passes 2000 --verbose --ignore=E501'
        language: system
        always_run: true
